language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xvfb xserver-xephyr python-pil scrot zenity gnumeric x11-utils x11-apps

install:
 - pip install coveralls
 - pip install -r requirements-test.txt
 - pip install --upgrade .
 
script:  
 - cd tests && nosetests -v --with-coverage --cover-package=pyvirtualdisplay .
 
after_success:
 - coveralls
